In [1]:
import numpy as np
import time

In [12]:
#import random 
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("Vectorized value = " + str(1000* (toc - tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("for loop time = " + str(1000*(toc-tic))+ "ms")

249741.43647657573
Vectorized value = 0.8540153503417969ms
249741.4364765833
for loop time = 540.5991077423096ms


In [11]:
a = np.random.randn(3, 3)
b = np.random.rand(3, 1)

print(a)
print(b)
tic = time.time()
c = a*b
toc = time.time()
print(c)

[[-2.41075034 -1.38165574 -0.50578752]
 [ 0.21456511 -1.09983265  0.11127684]
 [ 0.66611107 -1.64213298  1.48292864]]
[[0.21551873]
 [0.77285382]
 [0.90093946]]
[[-0.51956186 -0.2977727  -0.10900669]
 [ 0.16582746 -0.85000986  0.08600073]
 [ 0.60012575 -1.4794624   1.33602893]]


In [19]:

a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
'''
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
'''
print(a)
print(b)
print(c)
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 